
POST http://localhost:5281/api/registro_voo/cadastrar
Content-Type: application/json

{
    "NumeroVoo": 122,
    "Origem": "Brasil",
    "Destino": "Europa",
    "HrPartida": "05:00",
    "HrChegadaPrevista": "14:30",
    "TipoAviao": "Boeing 747-8",
    "Companhia": "Azul" 
}

###

GET http://localhost:5281/api/registro_voo/listar

### 

PUT http://localhost:5281/api/registro_voo/atualizar/1
Content-Type: application/json

{
  "HrPartida": "12:00",
  "HrChegadaPrevista": "32:30",
  "TemProblema" : true
}

# DELETE http://localhost:5281/api/registro_voo/deletar/


# //================================================================================================================


# POST http://localhost:5281/api/registro_tripulacao/cadastrar
# Content-Type: application/json

# {
#   "Nome": "Adriel",
#   "Cargo": "Piloto",
#   "Funcao": "pilotar o aviao",
#   "Qualificacoes": "PPL, CPL, ATPL, Certificação Médica, Habilitações de Voo, Treinamento de Emergência",
#   "HorarioTrabalho": "04:30 as 14:00",
#   "IdiomasFalados": "Portugues, ingles, espanhol",
#   "VooId" : 1
# }



# GET http://localhost:5281/api/registro_tripulacao/listar



# PUT http://localhost:5281/api/registro_tripulacao/atualizar/1
# Content-Type: application/json

# {
#     "Nome": "Robin",
# }


# DELETE http://localhost:5281/api/registro_tripulacao/deletar/1

# POST http://localhost:5281/api/verificacaoclimatica/cadastrar
# Content-Type: application/json

# {
#     "CondicoesMeteorologicas": "chuva",
#     "PrevisaoTempo": "05:00",
#     "AlertasTempestades": "14:30",
#     "CondicoesAdversas": "Boeing 747-8",
#     "vooId" : 1        
# }

# GET http://localhost:5281/api/verificacaoclimatica/listar

# PUT http://localhost:5281/api/verificacaoclimatica/atualizar/1
# Content-Type: application/json

# {
#     "CondicoesMeteorologicas": "chuva",
#     "PrevisaoTempo": "05:00",
#     "AlertasTempestades": "14:30",
#     "CondicoesAdversas": "Boeing 747-8"
# }

# DELETE http://localhost:5281/api/verificacaoclimatica/deletar/1

# GET http://localhost:5281/api/registro_passageiro/listar 

# POST http://localhost:5281/api/registro_passageiro/cadastrar
# {
# 	"Nome": "Adriel",
# 	"Sobrenome": "Roque",
# 	"NumeroDocumento" : "54312375634",
# 	"dataNascimento" : "1987-05-23",
# 	"Nacionalidade": "Alemão",
# 	"InformacoesContato": "adriel.roque@gmail.com",
# 	"Passaporte": "RD643123",
# 	"VooId" : 1
# }

# PUT http://localhost:5281/api/registro_passageiro/atualizar/1

# {
# 		"Nacionalidade" : "Brasileiro"
# }

# DELETE http://localhost:5281/api/registro_passageiro/deletar/1

# POST http://localhost:5281/api/carga/cadastrar
# Content-Type: application/json

# {
#     "peso": 123.45,
#     "descricao": "Bagagem para alguem importante",
#     "cargaPrioritaria": true,
#     "cargaComercial": false,
#     "passageiroId": 1
# }

# GET http://localhost:5281/api/carga/listar

# PUT http://localhost:5281/api/carga/atualizar/1

# {
#     "peso": 150.00,
#     "cargaPrioritaria": false,
#     "passageiroId": 2
# }

# DELETE http://localhost:5281/api/carga/deletar/1

