// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViagemProjeto.Models;

#nullable disable

namespace ViagemProjeto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ViagemProjeto.Models.Registro_Voo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Companhia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destino")
                        .HasColumnType("TEXT");

                    b.Property<string>("HrChegadaPrevista")
                        .HasColumnType("TEXT");

                    b.Property<string>("HrPartida")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroVoo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origem")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAviao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Registro_Voos");
                });
#pragma warning restore 612, 618
        }
    }
}
